In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df = sns.load_dataset('iris')

In [ ]:
print(df.head())

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X = df.drop('species',axis=1)
y = df['species']

In [10]:
X.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [20]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [21]:
model_knn.score(X_test,y_test)

1.0

In [33]:
from sklearn.svm import SVC
model_SVM = SVC(gamma='auto')

In [34]:
model_SVM.fit(X_train,y_train)

SVC(gamma='auto')

In [35]:
model_SVM.score(X_test,y_test)

1.0

In [37]:
from sklearn.model_selection import GridSearchCV

In [41]:
classifier = GridSearchCV(model_SVM, {
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
    
},cv=5,return_train_score=False)

In [42]:
classifier.fit(X , y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [43]:
classifier.cv_results_

{'mean_fit_time': array([0.00623937, 0.0043149 , 0.00390911, 0.00396872, 0.00407867,
        0.00486603, 0.0043551 , 0.00391326]),
 'std_fit_time': array([0.00192569, 0.00076372, 0.00019775, 0.00087162, 0.00029752,
        0.00082794, 0.00088478, 0.00021372]),
 'mean_score_time': array([0.00363774, 0.00298419, 0.00332236, 0.00281639, 0.00300751,
        0.00274177, 0.00312915, 0.00307636]),
 'std_score_time': array([0.00065996, 0.00058502, 0.0003476 , 0.00078827, 0.0008458 ,
        0.0006555 , 0.00082539, 0.00127075]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7])}

In [45]:
result = pd.DataFrame(classifier.cv_results_)

In [46]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006239,0.001926,0.003638,0.000660,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004315,0.000764,0.002984,0.000585,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003909,0.000198,0.003322,0.000348,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003969,0.000872,0.002816,0.000788,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004079,0.000298,0.003008,0.000846,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004866,0.000828,0.002742,0.000656,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.004355,0.000885,0.003129,0.000825,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003913,0.000214,0.003076,0.001271,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [47]:
result[['param_C', 'param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      30          rbf         0.960000
7      30       linear         0.960000

In [48]:
from sklearn.model_selection import RandomizedSearchCV

In [49]:
classifier_r = RandomizedSearchCV(model_SVM, {
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
    
},n_iter=4,cv=5,return_train_score=False)

In [50]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [51]:
results = pd.DataFrame(classifier_r.cv_results_)

In [52]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005513,0.001913,0.002994,0.000676,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
1,0.004615,0.001082,0.003316,0.000449,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
2,0.004117,0.000263,0.002887,0.000193,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
3,0.005321,0.001145,0.002653,0.000806,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.96,0.038873,4

In [53]:
results[['param_C', 'param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1       linear             0.98
1       1          rbf             0.98
2      10          rbf             0.98
3      30          rbf             0.96